language: generic

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - make quick-start -C ./docker/openwhisk-devtools/docker-compose/
  - docker-compose -f ./docker/docker-compose.yml up -d

script:
  - docker-compose -f ./docker/docker-compose.yml run meteoroid /bin/sh -c "pipenv install --system --dev && flake8 ./meteoroid && python ./meteoroid/manage.py test meteoroid/ && mkdocs build"
  - ./meteoroid/tests/meteoroidtest.sh
