version: '3'

services:
  mongo:
    image: mongo:3.6
    command: --nojournal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: meteoroid
      MONGO_INITDB_ROOT_PASSWORD: meteoroid_password
      MONGO_INITDB_DATABASE: meteoroid

  orion:
    image: fiware/orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  meteoroid:
    build: ../
    image: meteoroid/core:0.0.1
    depends_on:
      - migration
      - orion
    ports:
      - "8000:8000"
    command: python meteoroid/manage.py runserver 0.0.0.0:8000

  migration:
    build: ../
    image: meteoroid/core:0.0.1
    command: python meteoroid/manage.py migrate
    links:
      - mongo
    depends_on:
      - mongo
