version: '3'

services:
  mongo:
    image: mongo:3.6
    command: --nojournal
    restart: always

  orion:
    image: fiware/orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  meteoroid:
    build: ../
    image: meteoroid/core:0.0.1
    stdin_open: true
    tty: true
    depends_on:
      - migration
      - orion
    ports:
      - "8000:8000"
    volumes:
      - ../meteoroid:/opt/meteoroid/meteoroid
    command: python meteoroid/manage.py runserver 0.0.0.0:8000

  migration:
    build: ../
    image: meteoroid/core:0.0.1
    command: python meteoroid/manage.py migrate
    links:
      - mongo
    depends_on:
      - mongo
