version: '3'

services:
  mongo:
    image: mongo:3.6
    command: --nojournal

  orion:
    image: fiware/orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  meteoroid:
    build: ../
    image: meteoroid/core:0.0.1
    depends_on:
      - mongo
      - orion
    ports:
      - "8000:8000"
