apiVersion: v2
name: fiware
description: A Helm chart for FIWARE and Meteoroid

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

dependencies:
  - name: mongodb
    version: "7.10.10"
    repository: "@bitnami"
  - name: openwhisk
    version: "0.2.5"
    repository: "file://openwhisk-deploy-kube/helm/openwhisk/"
  - name: cp-helm-charts
    version: "0.5.0"
    repository: "https://confluentinc.github.io/cp-helm-charts/"
