apiVersion: v1
kind: Service
metadata:
  name: cratedb
  labels:
    {{- include "fiware.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: crate-admin
      port: 4200
      targetPort: crate-admin
      protocol: TCP
      nodePort: {{ .Values.quantumleap.db.nodePort.admin }}
    - name: crate
      port: 4300
      targetPort: crate
      protocol: TCP
      nodePort: {{ .Values.quantumleap.db.nodePort.crate }}
    - name: sql-port
      port: 5432
      targetPort: sql-port
      nodePort: 30432
  selector:
    {{- include "fiware.selectorLabels" . | nindent 4 }}
