apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    {{- include "fiware.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fiware.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fiware.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fiware.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.quantumleap.ui.image.name }}:{{ .Values.quantumleap.ui.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana-port
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_INSTALL_PLUGINS
              value: "https://github.com/orchestracities/grafana-map-plugin/archive/master.zip;grafana-map-plugin,grafana-clock-panel,grafana-worldmap-panel"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
