# Generated by Django 2.2.6 on 2019-11-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiware_service', models.CharField(blank=True, default='', max_length=64)),
                ('fiware_service_path', models.CharField(default='/', max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('name', 'fiware_service', 'fiware_service_path')},
            },
        ),
    ]
