# Generated by Django 2.2.8 on 2020-01-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191121_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiware_service', models.CharField(blank=True, default='', max_length=64)),
                ('fiware_service_path', models.CharField(default='/', max_length=64)),
                ('trigger_name', models.CharField(max_length=64)),
                ('rule_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='core.Function')),
            ],
            options={
                'unique_together': {('name', 'fiware_service', 'fiware_service_path')},
            },
        ),
    ]
